// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// inahull_cpp_multiple
LogicalVector inahull_cpp_multiple(List ahull_obj, NumericVector X, NumericVector Y);
RcppExport SEXP rollply_inahull_cpp_multiple(SEXP ahull_objSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type ahull_obj(ahull_objSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    __result = Rcpp::wrap(inahull_cpp_multiple(ahull_obj, X, Y));
    return __result;
END_RCPP
}
// lookup_in_wdw
LogicalVector lookup_in_wdw(NumericMatrix current_coords, NumericMatrix coords, double wdw);
RcppExport SEXP rollply_lookup_in_wdw(SEXP current_coordsSEXP, SEXP coordsSEXP, SEXP wdwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type current_coords(current_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type wdw(wdwSEXP);
    __result = Rcpp::wrap(lookup_in_wdw(current_coords, coords, wdw));
    return __result;
END_RCPP
}
