// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// inahull_cpp_multiple
LogicalVector inahull_cpp_multiple(List ahull_obj, NumericVector X, NumericVector Y);
RcppExport SEXP _rollply_inahull_cpp_multiple(SEXP ahull_objSEXP, SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type ahull_obj(ahull_objSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(inahull_cpp_multiple(ahull_obj, X, Y));
    return rcpp_result_gen;
END_RCPP
}
// lookup_in_wdw
LogicalVector lookup_in_wdw(NumericMatrix current_coords, NumericMatrix coords, double wdw);
RcppExport SEXP _rollply_lookup_in_wdw(SEXP current_coordsSEXP, SEXP coordsSEXP, SEXP wdwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type current_coords(current_coordsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type wdw(wdwSEXP);
    rcpp_result_gen = Rcpp::wrap(lookup_in_wdw(current_coords, coords, wdw));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rollply_inahull_cpp_multiple", (DL_FUNC) &_rollply_inahull_cpp_multiple, 3},
    {"_rollply_lookup_in_wdw", (DL_FUNC) &_rollply_lookup_in_wdw, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rollply(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
