# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lookup_in_wdw <- function(current_coords, coords, wdw) {
    .Call('rollply_lookup_in_wdw', PACKAGE = 'rollply', current_coords, coords, wdw)
}

